image: node:20-bullseye

stages:
  - fetch
  - build

variables:
  DOC_REPO_DIR: wb-idf-core

fetch_repo:
  stage: fetch
  image: node:20-bullseye
  variables:
    GIT_STRATEGY: none
  script:
    - apt-get update && apt-get install -y git
    - git clone https://matti122:${GITHUB_TOKEN}@github.com/WhirlingBits/wb-idf-core.git $DOC_REPO_DIR
  artifacts:
    paths:
      - $DOC_REPO_DIR

build_doxygen2docusaurus:
  stage: build
  dependencies:
    - fetch_repo
  script:
    # System-Doxygen und Graphviz installieren
    - apt-get update && apt-get install -y doxygen graphviz
    # xPack Doxygen2Docusaurus installieren
    - npm install -g @xpack/doxygen2docusaurus@2.0.0
    # In Repo wechseln
    - cd $DOC_REPO_DIR
    - mkdir -p docs/out
    # Doxygen ausführen, um XML-Dateien zu erzeugen
    - doxygen Doxyfile
    # xPack Doxygen2Docusaurus konvertiert XML zu MDX-Dateien
    - doxygen2docusaurus convert --input docs/out/xml --output docs/mdx
    # Artefakte sammeln
    - mkdir -p ../../dist
    - cp -r docs/mdx/* ../../dist/
