image: node:20-bullseye

stages:
  - fetch
  - build

variables:
  DOC_REPO_DIR: wb-idf-core

fetch_repo:
  stage: fetch
  image: node:20-bullseye
  variables:
    GIT_STRATEGY: none
  script:
    - apt-get update && apt-get install -y git
    - git clone https://matti122:${GITHUB_TOKEN}@github.com/WhirlingBits/wb-idf-core.git $DOC_REPO_DIR
  artifacts:
    paths:
      - $DOC_REPO_DIR

build_doxysaurus:
  stage: build
  script:
    - apt-get update && apt-get install -y doxygen
    - npm install -g @rnw-scripts/doxysaurus@latest
    - echo "📄 Copy config from wb-docs to wb-idf-core"
    - cp doxysaurus.config.json $DOC_REPO_DIR/
    - cd $DOC_REPO_DIR
    - doxygen -g Doxyfile
    - doxygen Doxyfile
    - echo "📚 Build Doxysaurus documentation"
    - npx doxysaurus build --config ./doxysaurus.config.json
    - cd ..
    - mkdir -p dist
    - cp -r $DOC_REPO_DIR/build/* dist/
  dependencies:
    - fetch_repo
  artifacts:
    paths:
      - dist
    expire_in: 1 week