image: node:20

stages:
  - fetch
  - build

variables:
  DOC_REPO_DIR: wb-idf-core

fetch_repo:
  stage: fetch
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://gitlab.whirlingbits.de/whirlingbits/wb-idf-core.git $DOC_REPO_DIR
  artifacts:
    paths:
      - $DOC_REPO_DIR

build_doxysaurus:
  stage: build
  script:
    - npm install -g @rnw-scripts/doxysaurus
    - cd $DOC_REPO_DIR
    - npx doxysaurus build
    - cd ..
    - mkdir -p dist
    - cp -r $DOC_REPO_DIR/build/* dist/
  dependencies:
    - fetch_repo
  artifacts:
    paths:
      - dist
    expire_in: 1 week