image: node:20

stages:
  - fetch
  - build

variables:
  GIT_STRATEGY: none
  DOC_REPO_DIR: wb-idf-core

fetch_repo:
  stage: fetch
  image: alpine:latest
  script:
    - apk add --no-cache git
    # Klone mit GitHub Token aus CI/CD Variable
    - git clone https://matti122:${GITHUB_TOKEN}@github.com/WhirlingBits/wb-idf-core.git $DOC_REPO_DIR
  artifacts:
    paths:
      - $DOC_REPO_DIR

build_doxysaurus:
  stage: build
  script:
    - npm install -g @rnw-scripts/doxysaurus
    - cp doxysaurus.config.js $DOC_REPO_DIR/
    - cd $DOC_REPO_DIR
    - npx doxysaurus build --config ./doxysaurus.config.js
    - cd ..
    - mkdir -p dist
    - cp -r $DOC_REPO_DIR/build/* dist/
  dependencies:
    - fetch_repo
  artifacts:
    paths:
      - dist
    expire_in: 1 week