image: node:20

stages:
  - fetch
  - build

variables:
  DOC_REPO_DIR: wb-idf-core

fetch_repo:
  stage: fetch
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache git
    - git clone https://matti122:${GITHUB_TOKEN}@github.com/WhirlingBits/wb-idf-core.git $DOC_REPO_DIR
  artifacts:
    paths:
      - $DOC_REPO_DIR

build_doxysaurus:
  stage: build
  script:
    - npm install -g @rnw-scripts/doxysaurus
    - echo "📄 Copy config from wb-docs to wb-idf-core"
    - cp doxysaurus.config.js $DOC_REPO_DIR/
    - cd $DOC_REPO_DIR
    - npx doxysaurus build --config ./doxysaurus.config.js
    - cd ..
    - mkdir -p dist
    - cp -r $DOC_REPO_DIR/build/* dist/
  dependencies:
    - fetch_repo
  artifacts:
    paths:
      - dist
    expire_in: 1 week